name: School Website
favicon: null
layout_spectrum: 0.44442684296518564
typography_spectrum: 0.7673652877565473
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7042295075953007
  lightness: 0.36321189999580383
  saturation: 0.7790985165629536
  rhythmicContrast: 0.24606871441937983
purpose: []
